name: 'B & A Photographers'
favicon: null
layout_spectrum: 0.51419
typography_spectrum: 0.72633
title: 'B & A Photographers'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#dddddf'
    - '#b1b2ac'
    - '#484848'
    - '#63d3c9'
  brandStrength: 0.75
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
