name: 'B & A Photographers'
favicon: null
layout_spectrum: 0.51419
typography_spectrum: 0.72633
title: 'B & A Photographers'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bda9a1'
    - '#220606'
    - '#572e20'
    - '#744c3c'
    - '#a65d61'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
